[覆盖更新大气层]
try:
download 'https://dl.awa.cool/hahappify/Hahappify.zip' /config/ultra/downloads.zip
del /switch/.packages/More
del /switch/.packages/More Menu
unzip /config/ultra/downloads.zip /
del /config/ultra/downloads.zip
del /atmosphere/contents/010000000000bd00/flags/boot2.flag
del /atmosphere/contents/4200000000000010/flags/boot2.flag
reboot

[提示]
[$]
;mode=table
;spacing=1
;gap=0
'没安装主题，无线手柄插件'=''
'以及联机插件，就可以覆盖大气层'=''
'也可以覆盖后去删除'=''
'目前支持20.5.0'=''
'数据较大，请耐心等待'=''

[在线更新]
[保留更新大气层]
try:
download 'https://dl.awa.cool/hahappify/Hahappify.zip' /config/ultra/Hahappify.zip
unzip /config/ultra/Hahappify.zip /update/
cp /whitelist.txt /update/
cp /blacklist.txt /update/
del /config/ultra/
reboot /bootloader/payloads/update.bin

[提示]
[$]
;mode=table
;spacing=1
;gap=0
'保留更新大气层会首先清空'=''
'除白名单以外的全部文件'=''
'然后针对白名单二次清理黑名单文件'=''
'黑白名单配合默认保留金手指mod、游戏'=''
'存档、安卓乌班图但是无法保留模拟器'=''
'如有需要自行添加白名单即可'=''
'按下保留更新大气层后'=''
'会跳转到bin界面，在update处按a或者电源键'=''
'即可正常保留更新'=''
''=''
'数据较大，请耐心等待'=''
''=''
''=''
''=''

[更新固件]
try:
download 'https://dl.awa.cool/hahappify/gu.zip' /config/ultra/gu.zip
unzip /config/ultra/gu.zip /
del /config/ultra/

[提示]
[$]
;mode=table
;spacing=1
;gap=0
'数据特大，15分钟'=''
'先更新大气层！先更新大气层！'=''
'下载完成后，进入相册'=''
'找到daybreak，一直按A就行了'=''