[音量控制]
try:
download 'https://gitee.com/gay-king/aio-switch-updater/releases/download/2.21.3/BrVol.zip' /config/ultra/downloads.zip
unzip /config/ultra/downloads.zip /
del /config/ultra/

[提示]
[$]
;mode=table
;spacing=1
;gap=0
'可以在任何情况'=''
'调节ns的声音'=''
'包括插在底座上'=''
''=''