[下载]
[*amiibo下载]
;mode=forwarder
package_source './amiibo/package.ini'

[下载]
[*动森amiibo下载]
;mode=forwarder
package_source './amiibo2/package.ini'

[下载]
[*修复游戏报错问题]
;mode=forwarder
package_source './debug/package.ini'

[下载]
[*FPS补丁下载]
;mode=forwarder
package_source './FPSLocker/package.ini'

[下载]
[*按键宏下载]
;mode=forwarder
package_source './Joycon/package.ini'

[下载]
[*音量控制]
;mode=forwarder
package_source './BrVol/package.ini'

[下载]
[*在线更新大气层]
;mode=forwarder
package_source './atmosphere/package.ini'

[下载]
[*安装极限超频]
;mode=forwarder
package_source './jxcp/package.ini'

[下载]
[*国行真实自动转区]
;mode=forwarder
package_source './zg/package.ini'