[eupld]
; 禁用将错误报告上传到 Nintendo
upload_enabled = u8!0x1

[usb]
; 为自制软件启用 USB 3.0
; 0 = USB 3.0 支持是系统默认的（通常禁用），1 = USB 3.0 支持已启用。
usb30_force_enabled = u8!0x1

[ro]
; 控制 RO 是否应放宽对 NRO 的验证。
;（注意：这通常不是必需的，可以使用 IPS 补丁。
ease_nro_restriction = u8!0x1

[lm]
; 控制 lm 是否应登录到 SD 卡。
; 请注意，当未启用日志管理器时，此设置不执行任何作。
; enable_sd_card_logging = u8!0x0
; SD 卡日志的输出目录。
; 请注意，当未启用日志管理器或未启用 SD 卡日志记录时，此设置不执行任何操作。
; sd_card_log_output_directory = str!atmosphere/binlogs

; 大气层自定义设置
[erpt]
; 开启或关闭自动清理erpt报告。1：保留报告，0：清理报告
disable_automatic_report_cleanup = u8!0x0

[atmosphere]
; 在一定毫秒数后自动重启。
; 如果字段不存在或为 0，则 fatal 将无限期等待用户输入。
fatal_auto_reboot_interval = u64!0x2710

; 使电源菜单的“重新启动”按钮重新启动到有效负载。
; 正常重启设置为“normal”，rcm 重启设置为“rcm”
power_menu_reboot_function = str!payload

; 控制 dmnt 作弊开关是否默认开启或关闭。
; 1 = 默认开启，0 = 默认关闭。
dmnt_cheats_enabled_by_default = u8!0x0

; 控制 dmnt 是否应始终保存作弊切换状态
; 在新游戏启动时恢复。1 = 始终保存切换，0 = 仅在切换文件存在时保存切换。
dmnt_always_save_cheat_toggles = u8!0x1

; 为 HBL 启用写入 BIS 分区。
; 这可能对正常使用不利。
enable_hbl_bis_write = u8!0x0

; 为 HBL 启用读取 CAL0 分区。
; 这可能对正常使用不利。
enable_hbl_cal_read = u8!0x0

; 控制 fs.mitm 是否应重定向保存文件
; 到 SD 卡上的目录。
; 0 = 不重定向，1 = 重定向。
; 注意：实验性
; 如果您不知道自己在做什么，请先不要碰它。
; fsmitm_redirect_saves_to_sd = u8!0x0

; 控制 am 是否将系统设置“DebugModeFlag”视为
; 启用或禁用。
; 0 = 禁用（非调试模式），1 = 启用（调试模式）
; enable_am_debug_mode = u8!0x0

; 控制是否启用 dns.mitm
; 0 = 禁用，1 = 启用
; enable_dns_mitm = u8!0x1

; 控制 dns.mitm 是否使用默认重定向
; 用户的 hosts 文件中指定的任何内容。
; 0 = 禁用（使用主机文件内容），1 = 启用（使用默认值和主机文件内容）
; add_defaults_to_dns_hosts = u8!0x1

; Controls whether dns.mitm logs to the sd card for debugging
; 0 = Disabled, 1 = Enabled
; enable_dns_mitm_debug_log = u8!0x0

; 控制是否启用 htc
; 0 = 禁用，1 = 启用
; enable_htc = u8!0x0

; 控制是否启用大气的日志管理器
; 请注意，启用 htc 时，此设置将被忽略（并被视为 1）。
; 0 = 禁用，1 = 启用
enable_log_manager = u8!0x0

; 控制是否将蓝牙配对数据库重定向到 SD 卡（在 sysmmc/所有 emummc 之间共享）
; 注意：在 <13.0.0 上，数据库大小为 10 而不是 20;在 13.0.0 之前启动将截断数据库。
; 0 = 禁用，1 = 启用
enable_external_bluetooth_db = u8!0x1

; 启动90DNS与任天堂服务器屏蔽
enable_dns_mitm = u8!0x1
add_defaults_to_dns_hosts = u8!0x1


[hbloader]
; 控制作为小程序运行时自制堆的大小。
; 如果设置为零，则所有可用的小程序内存都用作堆。
; 默认值为零。
applet_heap_size = u64!0x0

; 控制作为小程序运行时要保留的内存量
; 供其他小程序使用。如果出现以下情况，此设置不起作用
; applet_heap_size 为非零。默认值为 0x8600000。
applet_heap_reservation_size = u64!0x8600000

[capsrv]
; 取消视频和截图验证。可以让NS播放你放入的视频和图片
enable_album_screenshot_filedata_verification=u8!0x0
enable_album_movie_filehash_verification=u8!0x0
enable_album_movie_filesign_verification=u8!0x0

[am.gpu]
; 是否启用 GPU 任务自动调度功能。
; （0 = 关闭，1 = 开启）
gpu_scheduling_enabled=u8!0x1


[tc]
; 风扇相关的设置，关于手持和底座的风扇控制切换
; 这样就可以保证插上底座就自动切换到主机模式的转速 拔除底座自动切换到掌机模式的转速
; 也可根据自己的实际情况 只复制所需模式的相关代码
sleep_enabled = u8!0x0
holdable_tskin = u32!0xEA60
tskin_rate_table_console = str!”[[-1000000, 28000, 0, 0], [28000, 42000, 0, 51], [42000, 48000, 51, 102], [48000, 55000, 102, 153], [55000, 60000, 153, 255], [60000, 68000, 255, 255]]”
tskin_rate_table_handheld = str!”[[-1000000, 28000, 0, 0], [28000, 42000, 0, 51], [42000, 48000, 51, 102], [48000, 55000, 102, 153], [55000, 60000, 153, 255], [60000, 68000, 255, 255]]”


; 下面的参数可省电，但会影响真实系统的正版游玩操作。
; 下面的参数可省电，但会影响真实系统的正版游玩操作。
; 下面的参数可省电，但会影响真实系统的正版游玩操作。
; 下面的参数可省电，但会影响真实系统的正版游玩操作。
; 下面的参数可省电，但会影响真实系统的正版游玩操作。

[ns.notification]
; 禁止向任天堂服务器发送报告
enable_download_task_list = u8!0x0
enable_download_ticket = u8!0x0
enable_network_update = u8!0x0
enable_random_wait = u8!0x0
enable_request_on_cold_boot = u8!0x0
enable_send_rights_usage_status_request = u8!0x0
enable_sync_elicense_request = u8!0x0
enable_version_list = u8!0x0
retry_interval_min = u32!0x7FFFFFFF
retry_interval_max = u32!0x7FFFFFFF
version_list_waiting_limit_bias = u32!0x7FFFFFFF
version_list_waiting_limit_min = u32!0x7FFFFFFF

[account]
; 禁用游戏的账号验证功能
na_required_for_network_service=u8!0x0
na_license_verification_enabled=u8!0x0

[ns.rights]
; 禁用DLC的账号权限验证
skip_account_validation_on_rights_check=u8!0x1
next_available_time_of_unexpected_error=u32!0x7FFFFFFF

[friends]
; 禁用好友功能服务
background_processing=u8!0x0

[npns]
; 完全禁用推送通知功能，
background_processing=u8!0x0
sleep_periodic_interval=u32!0x7FFFFFFF
sleep_processing_timeout=u32!0x0
sleep_max_try_count=u32!0x0

[prepo]
; 完全关闭数据上传功能
transmission_interval_min=u32!0x7FFFFFFF
transmission_retry_interval_min=u32!0x7FFFFFFF
transmission_retry_interval_max=u32!0x7FFFFFFF
transmission_interval_in_sleep=u32!0x7FFFFFFF
statistics_save_interval_min=u32!0x7FFFFFFF
statistics_post_interval=u32!0x7FFFFFFF
save_system_report=u8!0x0

[olsc]
; 完全关闭云存档功能
default_auto_upload_global_setting=u8!0x0
default_auto_download_global_setting=u8!0x0
autonomy_registration_interval_seconds=u32!0x7FFFFFFF
network_service_license_info_cache_expiration_seconds=u32!0x7FFFFFFF
postponed_transfer_task_processing_interval_seconds=u32!0x7FFFFFFF
retry_offset_seconds=u32!0x7FFFFFFF
network_trouble_detection_span_seconds=u32!0x7FFFFFFF
network_connection_polling_interval_seconds=u32!0x7FFFFFFF
is_save_data_backup_policy_check_required=u8!0x0
is_global_transfer_task_autonomy_registration_enabled=u8!0x0
is_on_event_transfer_task_registration_enabled=u8!0x0
is_periodic_transfer_task_registration_enabled=u8!0x0


[ntc]
; 关闭系统时间自动校正
is_autonomic_correction_enabled=u8!0x0
autonomic_correction_interval_seconds=u32!0x7FFFFFFF
autonomic_correction_failed_retry_interval_seconds=u32!0x7FFFFFFF
autonomic_correction_immediate_try_count_max=u32!0x0
autonomic_correction_immediate_try_interval_milliseconds=u32!0x7FFFFFFF


[systemupdate]
; 禁用系统更新的自动尝试
bgnup_retry_seconds=u32!0x7FFFFFFF


[pctl]
; 关闭家长控制规则更新
intermittent_task_interval_seconds=u32!0x7FFFFFFF






