[修复游戏报错问题]
try:
del /SaltySD/exceptions.txt
download 'https://gitee.com/gay-king/aio-switch-updater/releases/download/2.21.3/debug.zip' /config/ultra/downloads.zip
unzip /config/ultra/downloads.zip /
del /config/ultra/

[提示]
[$]
;mode=table
;spacing=1
;gap=0
'当游戏打开就报错'=''
'先试着下载这个'=''
'重启生效'=''
'还会？开机时'=''
'长按音量加减'=''
'进维护模式后'=''
'按电源关机'=''
'如果还不行'=''
'看看是不是MOD原因'=''
'不是就重装游戏'=''