[fps-counter]
background_color=#1117
disable_screenshots=false
docked_font_size=40
handheld_font_size=40
layer_height_align=top
layer_width_align=left
text_color=#FFFF

[fps-graph]
background_color=#0007
border_color=#F80F
dashed_line_color=#8888
disable_screenshots=false
fps_counter_color=#4444
layer_height_align=top
layer_width_align=left
main_line_color=#FFFF
max_fps_text_color=#FFFF
min_fps_text_color=#FFFF
perfect_line_color=#0C0F
rounded_line_color=#F0FF
show_info=false

[full]
cat_color_1=#0FFF
cat_color_2=#FFFF
disable_screenshots=false
layer_width_align=left
refresh_rate=1
separator_color=#088F
show_deltas=true
show_fps=true
show_real_freqs=true
show_res=true
show_target_freqs=true
text_color=#8CFF

[game_resolutions]
background_color=#0007
cat_color=#2DFF
disable_screenshots=false
frame_offset_x=10
frame_offset_y=10
layer_height_align=top
layer_width_align=left
refresh_rate=10
text_color=#FFFF

[micro]
#replace_GB_with_MB_load=true
background_color=#0007
cat_color=#2DFF
disable_screenshots=false
docked_font_size=17
dtc_format=%H:%M
element_order=FPS+RES+CPU+GPU+RAM+READ+SOC+TMP+BAT+DTC
handheld_font_size=17
layer_height_align=top
real_freqs=true
real_volts=false
refresh_rate=1
replace_GB_with_RAM_load=true
separator_color=#2DFF
show=FPS+RES+CPU+GPU+RAM+SOC+BAT+DTC
show_full_cpu=false
show_full_res=false
show_soc_voltage=false
show_vdd2=false
show_vddq=false
text_align=Center
text_color=#FFFF
use_dtc_symbol=false
use_dynamic_colors=true

[mini]
#replace_MB_with_RAM_load=true
background_color=#0009
cat_color=#2DFF
disable_screenshots=false
docked_font_size=14
frame_offset_x=10
frame_offset_y=10
handheld_font_size=14
layer_height_align=top
layer_width_align=left
real_freqs=true
real_volts=true
refresh_rate=1
separator_color=2DFF
show=CPU+GPU+RAM+TMP+FPS+BAT+RES
show_RAM_load_CPU_GPU=false
show_full_res=true
show_show_vdd2=true
spacing=4
text_color=#FFFF
use_dtc_symbol=false

[status-monitor]
average_gpu_load=false
battery_avg_iir_filter=false
battery_time_left_refreshrate=60
font_cache=true
key_combo=L+DDOWN
