[status-monitor]
battery_avg_iir_filter=false
battery_time_left_refreshrate=60
average_gpu_load=false

[full]
refresh_rate=1
layer_width_align=left
show_real_freqs=true
show_deltas=true
show_target_freqs=true
show_fps=true
show_res=true

[mini]  
refresh_rate=1
layer_width_align=left
layer_height_align=top
handheld_font_size=15
docked_font_size=15
spacing=8
real_freqs=true
real_volts=true
show=CPU+GPU+RAM+SOC+BAT+FPS+RES
show_full_cpu=true
show_full_res=true
replace_MB_with_RAM_load=false
background_color=#0009
separator_color=2DFF
cat_color=#2DFF
text_color=#FFFF

[micro]
#横幅模式

refresh_rate=1
#调整刷新率，不要动

layer_height_align=top
#调整横幅位置，top为顶部，bottom为底部

handheld_font_size=15
#调整手持模式时横幅字体大小，15为标准大小，根据需要调整

docked_font_size=15
#调整底座模式时横幅字体大小，15为标准大小，根据需要调整

real_freqs=true
#是否显示真实频率

real_volts=true
#是否显示真实电压

show=FPS+RES+CPU+GPU+RAM+SOC+BAT
#显示哪些项目，顺序为从左到右。
# FPS为帧数。RES为分辨率。CPUGPURAM不用说了。SOC为芯片温度（含风扇转速）。
# TMP为同时显示SOC和PCB和SKIN的温度（含风扇）。BAT为电池相关项。
#注意SOC和TMP只能选择一个。

show_full_cpu=false
#是否显示每个核心的的CPU占用

show_full_res=false
#是否显示完整的分辨率（别动他）

#replace_GB_with_RAM_load=false
#如果去掉注释改为true，会显示已用多少内存（如3.8/4GB）而不是百分比占用

background_color=#0009
separator_color=2DFF
cat_color=#2DFF
text_color=#FFFF
#颜色项按需调整，默认就很好看

show_time=true
#在最右边显示系统时间，方便游戏的时候看时间（如果没有添加BAT则不显示）

show_volt_unit=false
#是否显示电压的单位mV，false则不显示

show_desktop_FPS_RES=true
#是否在桌面模式下强制显示FPS和RES（只会显示0.0，为了美观，因为桌面无法读取相关参数）

[fps-counter]
layer_width_align=left
layer_height_align=top
handheld_font_size=24
docked_font_size=24
text_color=#0F0F
background_color=#111A

[fps-graph]
layer_width_align=left
layer_height_align=top
max_fps_text_color=#FFFF
min_fps_text_color=#FFFF
background_color=#111A
fps_counter_color=#4444
border_color=#F77F
dashed_line_color=#8888
main_line_color=#FFFF
rounded_line_color=#F0FF
perfect_line_color=#0C0F
show_info=true

[game_resolutions]
refresh_rate=10
layer_width_align=left
layer_height_align=top
background_color=#1117
cat_color=#FFFF
text_color=#FFFF
