;title='游戏模组'
;creator='CatcherITGF, ppkantorski, 1bit.ai'
;color=red
[游戏模组]
[*王国之泪]
;mode=forwarder
package_source './TOTK UltraCam/package.ini'

[*旷野之息]
;mode=forwarder
package_source './BOPW UltraCam/package.ini'

[*智慧的再现]
;mode=forwarder
package_source './EoW UltraCam/package.ini'


[Package Info]
