[安装极限超频]
try:
del /atmosphere/contents/00FF0000636C6BFF
del /config/sys-clk/
del /switch/sys-clk-manager.nro
del /switch/sys-clk.nro
del /switch/.overlays/sys-clk-overlay.ovl
del /switch/.overlays/sys-clk.ovl
download 'https://gitee.com/gay-king/aio-switch-updater/releases/download/2.21.3/jxcp.zip' /config/ultra/downloads.zip
unzip /config/ultra/downloads.zip /
del /config/ultra/downloads.zip

[提示]
[$]
;mode=table
;spacing=1
;gap=0
'安装后，重启系统'=''
'进系统报错就进虚拟安全'=''
''=''