[FPSLocker 补丁 - 更新]
try:
download 'https://dl.awa.cool/scy/FPSLocker-Warehouse/fpslocker.zip' /config/ultra/downloads.zip
unzip /config/ultra/downloads.zip /config/ultra/
mv /config/ultra/SaltySD/ /SaltySD/
mv /config/ultra/atmosphere/ /atmosphere/
del /config/ultra/

[重要信息]
[$]
;mode=table
;spacing=1
;gap=0
'下载服务来自https://nsw.awa.cool/'=''
''=''
'维护者 huangsam; Hahappify; 葡萄糖酸菜鱼'=''