;title='超频配置'
;creator='Thanks to ppkantorski, B3711'
;version=1.6.9-参数调整
;color=red


[@超频参数]



[超频参数]
[*CPU]
;mode=forwarder
package_source './Data/Tuner/CPU.ini'


[*GPU]
;mode=forwarder
package_source './Data/Tuner/GPU.ini'


[*RAM]
;mode=forwarder
package_source './Data/Tuner/RAM.ini'






[您的配置]
[*当前配置]
;mode=forwarder
package_source './Data/Presets/Current Main.ini'



[您的配置]
[*自动配置]
;mode=forwarder
package_source './Data/Presets/Presets Manager.ini'
cp './Data/Presets/Boot Presets.ini' './Data/Presets/boot_package.ini'




[您的配置]
[*备份管理]
;mode=forwarder
package_source './Data/Presets/Backup Manager.ini'


[您的配置]
[Package Info]












