[按键宏下载]
try:
download 'https://gitee.com/gay-king/aio-switch-updater/releases/download/2.21.3/Joycon.zip' /config/ultra/downloads.zip
unzip /config/ultra/downloads.zip /
del /config/ultra/

[提示]
[$]
;mode=table
;spacing=1
;gap=0
'能录制并重播按键操作'=''
'开启前请先更换特斯拉的'=''
'唤醒键，不然会报错'=''