[config]
; hekate基础设置
; 0 开机进hekate界面，1 开机进入下面的第一项也就是虚拟系统
autoboot=0

; 0：从 hekate_ipl.ini 读取自动启动启动条目，
; 1：从 ini 文件夹读取（ini 文件以 ASCII 顺序排序）。
autoboot_list=0

; 开机等待你按音量键进入hekate的时间，单位秒
bootwait=2

; hekate的背光亮度
backlight=100

; 默认不要动
autohosoff=1
autonogc=1
updater2p=1

[虚拟系统]
; 设置package3路径
; hekate会从中提取kips, exosphere, warmboot, mesophere
pkg3=atmosphere/package3
; 强制使用 emuMMC
emummcforce=1
; 设置kip路径
kip1=atmosphere/kips/*
; 设置hekate开机图
logopath=bootloader/bootlogo.bmp
; hekate 启动项的图标
icon=bootloader/res/icon_EMU.bmp
; 启动大气层虚拟系统
id=Atm-Emu

[正版系统]
pkg3=atmosphere/package3
; 启动的时候屏幕掉emuMMC
emummc_force_disable=1
; 启动正版系统引导
stock=1
icon=bootloader/res/icon_OFW.bmp
; 启动官方正版系统
id=OFW-SYS


[虚拟安全模式]
; 不加载KIP让超频功能失效
pkg3=atmosphere/package3
emummcforce=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/icon_safe_EMU.bmp