;title='系统控制'
;creator='Hahappify'
;version=1.0
;color=red

[音量]
;mode=named_step_trackbar
;unlocked=false
json_source '[{"name": "0", "value": "0"}, {"name": "1", "value": "1"}, {"name": "2", "value": "2"}, {"name": "3", "value": "3"}, {"name": "5", "value": "5"}, {"name": "7", "value": "7"}, {"name": "9", "value": "9"}, {"name": "11", "value": "11"}, {"name": "14", "value": "14"}, {"name": "17", "value": "17"}, {"name": "20", "value": "20"}, {"name": "24", "value": "24"}, {"name": "29", "value": "29"}, {"name": "34", "value": "34"}, {"name": "40", "value": "40"}, {"name": "47", "value": "47"}, {"name": "55", "value": "55"}, {"name": "64", "value": "64"}, {"name": "74", "value": "74"}, {"name": "86", "value": "86"}, {"name": "100", "value": "100"}]' name
volume {json_source(*,value)}
set-ini-val '/switch/.packages/SystemControl/config.ini' 静音 footer Off
set-ini-val '/switch/.packages/SystemControl/config.ini' 取消ultrahand控制 footer Off
refresh

[静音]
;mode=toggle
;default=false
ini_file '/switch/.packages/SystemControl/config.ini'

on:
  volume 0

off:
  volume {ini_file(音量,value)}

[取消ultrahand控制]
;mode=toggle
;default=false
ini_file '/switch/.packages/SystemControl/config.ini'

on:
  volume 100

off:
  volume {ini_file(音量,value)}


[Package Info]