;color=#2277FF
;show_widget=true



[@主菜单]

[UltraCam 3.0.0 - 安装]
[安装]
try:
/config/ultrahand/downloads/UltraCam-TotKN.zip
unzip /config/ultrahand/downloads/UltraCam-TotKN.zip /config/ultrahand/downloads/app/
move /config/ultrahand/downloads/app/ /

[卸载]
delete /atmosphere/contents/0100F2C0115B6000/exefs/
delete /atmosphere/contents/0100F2C0115B6000/romfs/UltraCam/
delete /atmosphere/exefs_patches/ZeldaToTK_TripleBuffer/
delete /UltraCam/

cp './TotKN Main.ini' './TotK.ini'
cp './TotKN Main.ini' '/config/UltraNX/TotK.ini'

exec TotKN
refresh


[Gap]
;mode=table
;background=false
;gap=17

[Info]
;mode=table
;gap=5
'查看控制'= '{右方向键}'
'支持版本:' =  '1.1.X  1.2.X  1.4.X'

[屏幕]

[底座模式分辨率?新增]
;mode=named_step_trackbar
;unlocked=true
json_source '[{"name":"720p", "width":"1280", "height":"720"}, {"name":"900p", "width":"1600", "height":"900"}, {"name":"1080p", "width":"1920", "height":"1080"}]' name
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution Width {json_source(*,width)}
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution Height {json_source(*,height)}

[Gap]
;mode=table
;background=false
;gap=5

[Info]
;mode=table
;background=false
;end_gap=5
;gap=17
'1080p仅适用于8GB版本'= ''


[手持模式分辨率?新增]
;mode=named_step_trackbar
;unlocked=true
json_source '[{"name":"540p", "width":"960", "height":"540"}, {"name":"576p", "width":"1024", "height":"576"}, {"name":"720p", "width":"1280", "height":"720"}]' name
set-ini-val /atmosphere/contents/01008CF01BAAC000/romfs/UltraCam/maxlastbreath.ini Handheld Width {json_source(*,width)}
set-ini-val /atmosphere/contents/01008CF01BAAC000/romfs/UltraCam/maxlastbreath.ini Handheld Height {json_source(*,height)}

[帧率限制?新增]
;mode=named_step_trackbar
;unlocked=true
list_source '(30.00, 45.00, 60.00)'
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini UltraCamFPS MaxFPS {list_source(*)}

[菜单帧率限制?新增]
;mode=named_step_trackbar
;unlocked=true
list_source '(30.00, 45.00, 60.00)'
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini UltraCamFPS mMenuFPS {list_source(*)}

[视野?新增]
;mode=named_step_trackbar
;unlocked=true
list_source '(50, 55, 60, 65, 70, 75, 80, 85, 90)'
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Gameplay Fov {list_source(*)}







[设置]

[阴影分辨率?新增]
;mode=named_step_trackbar
;unlocked=true
list_source '(128, 256, 512, 1024)'
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution ShadowResolution {list_source(*)}

[渲染距离?新增]
;mode=named_step_trackbar
;unlocked=true
list_source '(10000, 15000, 20000, 25000, 30000, 35000, 40000)'
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution RenderDistance {list_source(*)}

[画质提升?新增]
;mode=toggle
on:
   set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution QualityImprovements True
off:
   set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution QualityImprovements False

[快速近似抗锯齿（FXAA）?新增]
;mode=toggle
on:
   set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution FXAA True
off:
   set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Resolution FXAA False



[其他]

[自由相机模式下隐藏UI?新增]
;mode=toggle
on:
   set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini UltraCam AutoHideUI True
off:
   set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini UltraCam AutoHideUI False

[摇杆垂直灵敏度?新增]
;mode=named_step_trackbar
;unlocked=true
list_source '(1.0, 1.1, 1.2, 1.3, 1.4, 1.5)'
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Gameplay Stick_Vertical_Speed {list_source(*)}

[摇杆水平灵敏度?新增]
;mode=named_step_trackbar
;unlocked=true
list_source '(1.0, 1.1, 1.2, 1.3, 1.4, 1.5)'
set-ini-val /UltraCam/TOTK/Config/maxlastbreath.ini Gameplay Stick_Horizontal_Speed {list_source(*)}






[@控制设置]

[操作按键]
[Info]
;mode=table
;spacing=12
;gap=30
'打开菜单' = '{ZL} + {ZR} + {左摇杆按下}'
'自由相机 开启/关闭' = '按住 {ZL} + {下方向键}'

[Info]
;mode=table
;spacing=12
;gap=0
'' = '当自由相机模式开启时：                                   '
'加速增加/减少' = '按住 {ZR}/{ZL}'
'向下/向上飞行' = '{L}/{R}'
'向左/向右倾斜' = '{Y}/{A}'
'锁定/解锁移动' = '{下方向键}'
'时间快进/后退' = '{加号键}/{减号键}'
'停止游戏内时间' = '按住 {ZR} + {减号键}'
'改变天气' = '按住 {ZR} + {加号键}'
'将林克传送到相机位置' = '按住 {ZR} + {下方向键}'
'暂停世界/游戏AI' = '按住 {ZL} + {减号键}'
'调整视野 +/-' = '按住 {下方向键} + {Y}/{A}'
'聚焦实体' = '{上方向键}'
'重置视野和倾斜角度' = '{左摇杆按下}'
